tof_sensor:
  ros__parameters:
    sensor_timeout_ms: 500 # [ms]
    sensor_frequency: 48.0 # [Hz]
imu_sensor:
  ros__parameters:
    sensor_frequency: 100.0 # [Hz]
kalman_filter:
  ros__parameters:
    timer_frequency: 100.0 # [Hz]
    ground_to_base_height: 400.81087 # [mm]
    range_filter_alpha: 0.3
    range_filter_beta: 0.025